### ISSUE TITLE
Use DTOs instead of dealing with entities directly

### ISSUE THREAD

**Issue by dvt32** [alialdev/projects#1]
Instead of modifying & returning the entities in the REST controllers, use DTOs (`MovieDto`, `TvShowDto`, etc).

More info here: https://www.baeldung.com/java-entity-vs-dto

**Comment by dvt32** [comment]
You may also use MapStruct for mapping entities to DTOs and vice-versa. More info here: https://www.baeldung.com/mapstruct

**Comment by ali-al-fntext** [comment]
I have created DTO's and implemented MapStruct
