### ISSUE TITLE
Use an abstract class which entities extend

### ISSUE THREAD

**Issue by dvt32** [alialdev/projects#2]
Some entities share many of the same fields, so it'd be better to have a common abstract class, which they extend (something like a `Media` class).

More info on how to implement it with JPA/Hibernate: https://www.baeldung.com/hibernate-inheritance

**Comment by dvt32** [comment]
Will be included in the next weeks' tasks.

**Comment by ali-al-fntext** [comment]
I already implemented super classes Media and MediaDto to my code.
