### ISSUE TITLE
Setup a unidirectional relationship between genres & media items

### ISSUE THREAD

**Issue by dvt32** [alialdev/projects#4]
We don't need to have a bidirectional relationship between genres and media items (movies, TV shows, etc). In other words, in `Genre` we don't need to have `movies`, `tvShows`, because we're not querying media items by genre (we're not doing "find all movies by genre" operations, for example).

You may also look into `@JsonIgnore`. See more info here:
- https://www.baeldung.com/jackson-bidirectional-relationships-and-infinite-recursion
- https://stackoverflow.com/questions/37392733/difference-between-jsonignore-and-jsonbackreference-jsonmanagedreference

**Comment by ali-al-fntext** [comment]
I have deleted bidirectional relationships and problem is solved. No need for @JsonIgnore at the moment
