### ISSUE TITLE
Fix REST API design for endpoints

### ISSUE THREAD

**Issue by dvt32** [alialdev/projects#5]
Instead of having endpoints like `/movies/list` & `/movies/add`, endpoints' name should be something like `/movies`, `/movies/{id}` with the appropriate HTTP method (GET, POST, PUT, DELETE) deciding what happens when the endpoint is used.

You can see some REST API best practices here: https://www.freecodecamp.org/news/rest-api-best-practices-rest-endpoint-design-examples

**Comment by ali-al-fntext** [comment]
Done
